import Navbar from "../components/PageLayouts/AppLayout/Navbar";
import Footer from "../components/Misc/Footer";

const Terms = () => {
    return <>
        <Navbar logoOnly unfixed/>
        {/* This component requires Tailwind CSS >= 1.5.1 and @tailwindcss/ui >= 0.4.0 */}
        <div className="relative py-16 bg-white overflow-hidden">
            <div className="hidden lg:block lg:absolute lg:inset-y-0 lg:h-full lg:w-full">
                <div className="relative h-full text-lg max-w-prose mx-auto">
                    <svg className="absolute top-12 left-full transform translate-x-32" width={404} height={384} fill="none" viewBox="0 0 404 384">
                        <defs>
                            <pattern id="74b3fd99-0a6f-4271-bef2-e80eeafdf357" x={0} y={0} width={20} height={20} patternUnits="userSpaceOnUse">
                                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
                            </pattern>
                        </defs>
                        <rect width={404} height={384} fill="url(#74b3fd99-0a6f-4271-bef2-e80eeafdf357)" />
                    </svg>
                    <svg className="absolute top-1/2 right-full transform -translate-y-1/2 -translate-x-32" width={404} height={384} fill="none" viewBox="0 0 404 384">
                        <defs>
                            <pattern id="f210dbf6-a58d-4871-961e-36d5016a0f49" x={0} y={0} width={20} height={20} patternUnits="userSpaceOnUse">
                                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
                            </pattern>
                        </defs>
                        <rect width={404} height={384} fill="url(#f210dbf6-a58d-4871-961e-36d5016a0f49)" />
                    </svg>
                    <svg className="absolute bottom-12 left-full transform translate-x-32" width={404} height={384} fill="none" viewBox="0 0 404 384">
                        <defs>
                            <pattern id="d3eb07ae-5182-43e6-857d-35c643af9034" x={0} y={0} width={20} height={20} patternUnits="userSpaceOnUse">
                                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
                            </pattern>
                        </defs>
                        <rect width={404} height={384} fill="url(#d3eb07ae-5182-43e6-857d-35c643af9034)" />
                    </svg>
                </div>
            </div>
            <div className="relative px-4 sm:px-6 lg:px-8">
                <div className="text-lg max-w-prose mx-auto mb-6">
                    <h1 className="mt-2 mb-8 text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">Privacy Policy</h1>
                    <p className="text-xl text-gray-500 leading-8">Sheetroom, Inc. (“we” or “Sheetroom”) is committed to protecting your privacy. This Privacy Policy describes our collection and use of personal information collected from visitors to our website and our mobile application(s) (collectively, our “Service”), including the Service offered at www.Sheetroom.com, and any other website, app, or online service which links to this Privacy Policy. “You” or “your” means a visitor or a user (whether logged in or not) of our Service.
                        A note about Student Data: Our Sheetroom Service may be used by schools, school districts, or teachers (collectively referred to as “Schools”) in a classroom setting. When Sheetroom contracts with a School to provide the Service through sheetroom.com to students in a classroom (“Students”), we may have access to Student Data (defined below). This Privacy Policy does not govern our access to Student Data. We consider Student Data to be highly confidential and our use of Student Data is governed by our agreements with the schools.
                        This Privacy Policy is incorporated into and is subject to our <a href="/terms" className="text-blue-600 font-bold">Terms of Service</a>, which governs your use of the Sheetroom Services.
                       </p>
                </div>
               <div className="prose prose-lg text-gray-500 mx-auto">
                   <h3 id="1-information-collected">1. Information Collected</h3>
                   <p>a. <em>Personal Data</em>. You can use parts of the Service without registering for an account or providing any other personal data. If you create an account on the Sheetroom Services, or communicate with Sheetroom, you may provide to Sheetroom certain information by which someone could personally identify you, such as your name, email or unique username (“Personally Identifiable Information”), as well as information about yourself such as your employment or level of schooling by which someone could not personally identify you (“Demographic Information”). When we link Demographic Information to your Personally Identifiable Information, we treat all of it as Personally Identifiable. We also collect information when you save or post content to the Service (“User Content”), authorize us to access your device camera and photo roll, and communicate with us. We refer to all of this data collectively as “Personal Data”. We may also collect Personal Data about you from a third party Internet site or service. For example, if you login to your Sheetroom account through Google or another authentication tool, or if you interact with Sheetroom on social media, we may collect the Personal Data you authorize that third party service to share.
                       b. <em>Usage Data</em>. We automatically collect certain technical usage information when you use the Sheetroom Services (“Usage Data”). Usage Data includes the information that your web browser or mobile application automatically sends to our servers whenever you visit. The Usage Data collected in our logs may include information such as your web request, Internet Protocol address, operating system, browser type, browser language, referring / exit pages and URLs, platform type, click history, domain names, landing pages, pages viewed and the order of those pages, the amount of time spent on particular pages, the date and time of your request, and whether you opened an email. Typically, this information is collected through log files, web beacons, browser cookies, or other device identifiers that may uniquely identify your browser or device. You may be able to set your web browser to refuse all cookies, and your mobile device to not provide your mobile device identifier. You may not be able to delete or disable cookies on certain mobile devices and/or certain browsers. For more information on cookies, visit  <a href="https://www.allaboutcookies.org/">www.allaboutcookies.org</a> . Remember, some features of the Sheetroom Services may not function properly if cookies or mobile device identifiers are not enabled. In addition, the Sheetroom Services may use third party analytics and bug tracking software (including, without limitation, Google Analytics and Bugsnag) to collect further Usage Data regarding the online usage patterns of our users and bugs in our Services. We may combine Usage Data with Personal Data in a manner that enables us to trace Usage Data to an individual user. Although we do our best to honor the privacy preferences of our visitors, we are not able to respond to Do Not Track signals from your browser at this time. We do not permit third party advertising networks or other third parties to collect information about your browsing behavior from our website for advertising purposes.</p>
                   <h3 id="2-use-of-your-information">2. Use of Your Information</h3>
                   <p>a. <em>Use</em>. We use your Personal Data and Usage Data (together, “User Information”) to operate, maintain, and provide to you the features and functionality of the Sheetroom Services and for related business purposes. We may use your User Information to (a) improve the quality and design of the Sheetroom Services and to create new features and services by storing, tracking, and analyzing user preferences; (b) remember information so that you will not have to re-enter it during your visit or the next time you use the Sheetroom Services; (c) provide custom, personalized content and information; (d) monitor aggregate metrics such as total number of visitors, pages viewed, etc.; and (e) diagnose and fix technology problems and otherwise plan for and enhance our Service. Sheetroom may provide personalized content and information to our users, including teachers, school administration officials, and other users associated with Schools. However, Sheetroom shall never use Student Data to engage in targeted advertising, nor shall Sheetroom direct advertising to student users on sheetroom.com, nor shall Sheetroom ever use any third-party advertising network on any Sheetroom Service.
                       b. <em>Communications Preferences</em>. We will not use your email address or other Personally Identifiable Information to send you marketing messages unless you provide your consent, or as part of a specific program or feature for which you will have the ability to opt-out. You can always opt-out of receiving promotional email from us by clicking on the “unsubscribe” feature at the bottom of each email or by adjusting your email subscription preferences in your settings. We may, however, use your email address without further consent for non-marketing or administrative purposes, such as notifying you of important Sheetroom Services changes or for customer service purposes.</p>
                   <h3 id="3-disclosure-of-your-information">3. Disclosure of Your Information</h3>
                   <p>a. <em>Your Publication</em>. You may, by using applicable sections of the Sheetroom Services (including sections which enable you to create graphs, perform lessons, provide comments, upload video and pictures), share your User Information, including Personally Identifiable Information and other content that you create or post to others accessing the Sheetroom Services.
                       b. <em>Service Providers</em>. We share User Information with our trusted third party service providers and other individuals who perform services on our behalf, for example, providing customer service support, hosting services, analytics and other services we utilize to help us provide our Service or conduct our business. These service providers access and use User Information only to provide services to Sheetroom under reasonable confidentiality terms.
                       c. <em>Partners</em>. At your direction, we may provide your User Information to our partners (“Partners”) that are integrated with the Sheetroom Network. For example, we may share certain User Information when you login to the Sheetroom Services using Google login and similar authentication tools. We may also share User Information when we provide the Service with a Partner, such as when we work with a school or educational institution to provide the Service to students. User Information that is shared with a third party Partner may be subject to that Partner’s privacy and data security policies. We are not responsible for the content or privacy and security practices and policies of the Partners. We encourage you to learn about our Partners’ privacy and security policies before providing them with your User Information or directing us to provide them with your User Information.
                       d. <em>Other Required Sharing</em>. We may share User Information: (i) if required to do so by law, or in the good-faith belief that such action is in compliance with state and federal laws (including, without limitation, copyright laws) or in response to a court order, subpoena, legal process or search warrant, or (ii) if we believe, in good faith, such action is appropriate or necessary to enforce our Terms of Service, to exercise our legal rights, to take precautions against liability, to investigate and defend ourselves against any claims or allegations, to assist government enforcement agencies, to protect the security or integrity of the Sheetroom Services, and to protect the rights, property, or personal safety of Sheetroom, Education Providers, our users or third parties.
                       e. <em>School Collaboration</em>. For Schools utilizing our School Collaboration functionality, school administration officials and teachers (collectively, “Admins”) may be able to share information, resources, and materials through the School Collaboration Features. Depending on School’s use of various features of the Service, an Admin may be able to share information with other Admins and/or invite other Admins to access, review, and edit School material. Sharing functionality will be determined by the School settings.
                       f. <em>Sharing of Student Work</em>. In some instances, Student Data, including, for example, student’s response to an assignment, (collectively, “Student Work”) may be visible to other students in the same classroom. A teacher or school administration official will be able to monitor any such Student Work and will be able to hide it at their discretion, for example if said Student Work is in violation of a school’s policies or the teacher’s desired classroom culture.
                       g. <em>Merger or Sale</em>. If we merge, sell, or otherwise transfer all or a portion of our business, we will not transfer your Personally Identifiable Information without first giving you the ability to opt-out of the transfer, unless the new owner intends to maintain and provide the applicable Sheetroom Services as a going concern, and provided that the new owner has agreed to data privacy standards no less stringent than our own. We may also transfer personal information – under the same conditions – in the course of mergers, acquisitions, bankruptcies, dissolutions, reorganizations, liquidations, similar transactions or proceedings involving all or a portion of our business.</p>
                   <h3 id="4-your-choices">4. Your Choices</h3>
                   <p>You may decline to submit Personally Identifiable Information through the Sheetroom Services, in which case Sheetroom or your School may not be able to provide certain Sheetroom Services to you. You may update or correct your name or email address, at any time by visiting your “Settings” link. You may also delete your account altogether there. With respect to User Information provided by your School, please reach out to your School to request removal or updates of such information. If you have any questions about reviewing, modifying, or deleting your information, or if you want to remove your name or comments from our website or publicly displayed content, you can contact us directly at  <a href="mailto:support@sheetroom.com">support@Sheetroom.com</a> . We may not be able to modify or delete your information in all circumstances.</p>
                   <h3 id="5-data-security">5. Data Security</h3>
                   <p>We care about the security of your information and employ physical, administrative, and technological safeguards designed to preserve the integrity and security of all information collected through our Service. Access to information is limited (through user/password credentials and, in some cases, two factor authentication) to those employees who require it to perform their job functions. We use industry standard SSL (secure socket layer technology) encryption to transfer personal information. Other security safeguards include but are not limited to data encryption, firewalls, physical access controls to buildings and files, and employee training. You can help protect against unauthorized access to your account and personal information by selecting and protecting your email account appropriately and limiting access to your computer and browser by signing off after you have finished accessing your account.</p>
                   <h3 id="6-children-s-privacy">6. Children’s Privacy</h3>
                   <p>Our Service is not directed to children under 13, unless and until a School has provided consent and authorization for a student under 13 to use the Service and for Sheetroom to collect information from such student. If you believe that we have inadvertently collected Personal Data from a child under 13 years of age without parental consent, then please alert us at  <a href="mailto:support@sheetroom.com">support@Sheetroom.com</a>  and we will promptly delete the child’s Personal Data from our systems.</p>
                   <h3 id="7-for-our-international-users">7. For Our International Users</h3>
                   <p>By using this Service, you consent to the transfer of your personal information to the United States and to the processing of your personal information in the United States in accordance with this Privacy Policy. You understand that your personal information will be subject to the laws of the United States, which may be different from those of your country of residence.</p>
                   <h3 id="8-contact-us">8. Contact Us</h3>
                   <p>Please feel free to contact us with any questions or comments about this Privacy Policy, your personal information, your consent, or your opt-in or opt-out choices as follows:</p>
                   <p>Email: contact@sheetroom.com</p>
                   <h3 id="6-children-s-privacy">9. Payment, Refunds, and Plan Changes</h3>
                   <p>Our Service is not directed to children under 13, unless and until a School has provided consent and authorization for a student under 13 to use the Service and for Sheetroom to collect information from such student. If you believe that we have inadvertently collected Personal Data from a child under 13 years of age without parental consent, then please alert us at  <a href="mailto:support@sheetroom.com">support@Sheetroom.com</a>  and we will promptly delete the child’s Personal Data from our systems.</p>
                   <p>a. <em>Updates</em>. This Privacy Policy may be revised periodically and this will be reflected in the “date last modified” set forth below. Your continued use of the Sheetroom Services following such update constitutes your agreement to the revised Privacy Policy.
                       b. <em>Last Modified</em>. This Privacy Policy was last modified September 2, 2020.</p>

               </div>

            </div>
        </div>
        <Footer/>
    </>
}

export default Terms
