import Navbar from "../components/PageLayouts/AppLayout/Navbar";
import Footer from "../components/Misc/Footer";

const Terms = () => {
    return <>
        <Navbar logoOnly unfixed/>
        {/* This component requires Tailwind CSS >= 1.5.1 and @tailwindcss/ui >= 0.4.0 */}
        <div className="relative py-16 bg-white overflow-hidden">
            <div className="hidden lg:block lg:absolute lg:inset-y-0 lg:h-full lg:w-full">
                <div className="relative h-full text-lg max-w-prose mx-auto">
                    <svg className="absolute top-12 left-full transform translate-x-32" width={404} height={384} fill="none" viewBox="0 0 404 384">
                        <defs>
                            <pattern id="74b3fd99-0a6f-4271-bef2-e80eeafdf357" x={0} y={0} width={20} height={20} patternUnits="userSpaceOnUse">
                                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
                            </pattern>
                        </defs>
                        <rect width={404} height={384} fill="url(#74b3fd99-0a6f-4271-bef2-e80eeafdf357)" />
                    </svg>
                    <svg className="absolute top-1/2 right-full transform -translate-y-1/2 -translate-x-32" width={404} height={384} fill="none" viewBox="0 0 404 384">
                        <defs>
                            <pattern id="f210dbf6-a58d-4871-961e-36d5016a0f49" x={0} y={0} width={20} height={20} patternUnits="userSpaceOnUse">
                                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
                            </pattern>
                        </defs>
                        <rect width={404} height={384} fill="url(#f210dbf6-a58d-4871-961e-36d5016a0f49)" />
                    </svg>
                    <svg className="absolute bottom-12 left-full transform translate-x-32" width={404} height={384} fill="none" viewBox="0 0 404 384">
                        <defs>
                            <pattern id="d3eb07ae-5182-43e6-857d-35c643af9034" x={0} y={0} width={20} height={20} patternUnits="userSpaceOnUse">
                                <rect x={0} y={0} width={4} height={4} className="text-gray-200" fill="currentColor" />
                            </pattern>
                        </defs>
                        <rect width={404} height={384} fill="url(#d3eb07ae-5182-43e6-857d-35c643af9034)" />
                    </svg>
                </div>
            </div>
            <div className="relative px-4 sm:px-6 lg:px-8">
                <div className="text-lg max-w-prose mx-auto mb-6">
                    <h1 className="mt-2 mb-8 text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">Terms and Conditions</h1>
                    <p className="text-xl text-gray-500 leading-8">Thank you for your interest in using the online services operated by Sheetroom, Inc. ("Sheetroom"). These Terms of Service ("Terms") govern your use of Sheetroom’s online services (collectively, the "Services"), including the services which are offered through (i) our website located at Sheetroom.com, and (ii) third party providers of educational services, such as schools, school districts, or teachers (collectively referred to as "Schools") that use our services at sheetroom.com.
                       </p>
                </div>
               <div className="prose prose-lg text-gray-500 mx-auto">
                   <h3 id="1-our-services">1. Our Services</h3>
                   <p>The Sheetroom Services enable teachers to easily build beautiful online assignments. You can use our drag and drop editor to build assignments that look great on web, mobile, and print. Students can join classes for an easy way to receive and turn in classwork. By using the Sheetroom Services, you agree to be bound by these Terms and to the collection and use of your information as described in our  <a href="/privacy">Privacy Policy</a> . If you do not agree to these Terms, you are not permitted to use the Sheetroom Services.</p>
                   <h3 id="2-eligibility-and-authority">2. Eligibility and Authority</h3>
                   <p>If you are agreeing to these Terms on behalf of a school, school district, or other educational institution (collectively, a “School”) for the purpose of providing the Sheetroom Service to students through sheetroom.com (“Students”), you represent and warrant that you are an authorized representative of the School and you agree to these Terms on the School’s behalf.
                       The U.S. Children’s Online Privacy and Protection Act (“COPPA”) requires that online service providers obtain verifiable parental consent before collecting personal information from children under 13. If you are a School providing the Service to children under 13 (whether in the U.S. or elsewhere), you represent and warrant that you have received consent from Parents, or have the authority to provide consent on behalf of parents, for us to collect information from students before allowing children under 13 to access Sheetroom Services. We recommend that all Schools provide appropriate disclosures to students and parents regarding their use of service providers such as Sheetroom.</p>
                   <h3 id="3-personal-information-and-student-data">3. Personal Information and Student Data</h3>
                   <p>This Section 3 applies to a School’s use of the Sheetroom Service through sheetroom.com.
                       When Sheetroom is used by a School for an educational purpose, Sheetroom may collect or have access to Student Data that is provided by the School or by the Student. “Student Data” is personal information that is directly related to an identifiable Student and may include “educational records” as defined by the Family Educational Rights and Privacy Act (“FERPA”), 20 U.S.C. § 1232(g).
                       <em>Confidentiality</em>. Sheetroom agrees to treat Student Data as confidential and not to share it with third parties other than as described in these Terms, and in our  <a href="/privacy">Privacy Policy</a>.
                       <em>Student Data Access</em>. You authorize Sheetroom to access or collect Student Data for the purpose of providing the Service. In the U.S., Sheetroom shall collect and process Student Data as a School Official with a legitimate educational interest pursuant to FERPA 34 CFR Part 99.31(a)(1). As between the parties, the School or the Student owns and controls the Student Data. Sheetroom does not own or control, or license such Student Data, except as to provide the Service and as described in these Terms.
                       <em>Personal Information and Student Data Consents and Authority</em>. If you are School User, you represent and warrant that you have provided appropriate disclosures to your School and to parents regarding your sharing such Personal Information with Sheetroom. Both Parties agree to uphold their obligations under the Family Educational Rights and Privacy Act (“FERPA”), the Protection of Pupil Rights Amendment (“PPRA”), and the Children’s Online Privacy and Protection Act (“COPPA”) and applicable State laws relating to student data privacy. Sheetroom relies on each School to obtain and provide appropriate consent and disclosures, if necessary, for Sheetroom to collect any Student Data, including the collection of Student Data directly from students under 13, as permitted under COPPA. You agree to comply with these Terms and all laws and regulations governing the protection of personal information, including children’s information, and the sharing of student education records.
                       <em>Use of Student Data</em>. By submitting or providing us access to Student Data, you agree that Sheetroom may use the Student Data solely for the purposes of (i) providing the Service, (ii) improving and developing our Service, (iii) enforcing our rights under these Terms, and (iv) as permitted with the School’s or the User’s consent. Sheetroom shall not use Student Data to engage in targeted advertising.
                       <em>Use of Anonymized Student Data</em>. You agree that we may collect and use data derived from Student Data for our own purposes, such as for product development, research analytics, and marketing our Service, provided that such data will be de-identified and/or aggregated to reasonably avoid identification of a specific individual.
                       <em>Use of Personal Information for Marketing</em>. You agree that Sheetroom may provide customized content, advertising, and commercial messaging to school or district administrative users and teachers from time to time, provided that such advertisements shall not be based on Student Data. For emphasis, and without limitation, Sheetroom shall never use Student Data to engage in targeted advertising, nor shall Sheetroom direct advertising to student users on sheetroom.com.
                       <em>Third-Party Service Providers</em>. You acknowledge and agree that Sheetroom may provide access to Student Data to our employees and service providers, which have a legitimate need to access such information in order to provide their services to us. We and our employees, affiliates, service providers, or agents involved in the handling, transmittal, and processing of Student Data will be required to maintain the confidentiality of such data.
                       <em>Student Data Retention and Deletion Requests</em>. Schools may request that we delete Student Data in our possession at any time by providing such a request in writing, except that Sheetroom shall not be required to delete content a Student shared to public areas of the Service. We shall respond to the deletion request as soon as possible, but in most instances within 45 days, other than for data stored on backup tapes which shall be deleted in the ordinary course of business. For inactive accounts, we delete or de-identify Student Data in our possession after a period of dormancy or at the request of a Parent. A Parent seeking to modify, correct, or delete personal information in a Student Account that is connected to an active School account will be instructed to contact the School to discuss data deletion or modification. We are not required to delete data that has been derived from Student Data so long as it has been anonymized such that it does not reasonably identify an individual. Similarly, we are not required to delete information which a Student or parent has saved or transferred to a personal account.
                       <em>Data Breach Notification</em>. We have implemented administrative, physical and technical safeguards designed to secure Personal Information, including Student Data, from unauthorized access, disclosure and use. In the event we have a reasonable, good faith belief that an unauthorized party has gained access to or been disclosed Student Data (a “Security Event”), that we have collected or received through the Service, we will promptly notify the School. If, due to a Security Event which is caused by the acts or omissions of Sheetroom or its agents, a notification to an individual, organization or government agency is required under applicable privacy laws, the School shall be responsible for the timing, content, and method of any such legally-required notice and compliance with such laws and Sheetroom shall indemnify the School for costs related to legally-required notifications. With respect to any Security Event which is not caused by the acts or omissions of Sheetroom or its agents, Sheetroom shall reasonably cooperate with School’s investigation of the Security Event, as School requests, at School’s reasonable expense. Sheetroom shall be responsible for the timing, content, cost and method of notice and compliance with such laws as they relate to User accounts that are not associated with a School account.</p>
                   <h3 id="4-your-responsibilities">4. Your Responsibilities</h3>
                   <p>You agree:
                       a. that you are responsible for obtaining and maintaining all equipment and services needed for access to and use of the Sheetroom Services and for paying all charges related thereto; and
                       b. not to use the Sheetroom Services to:
                       i. violate any third party rights or any local, state, national, or international law or regulation;
                       ii. transmit or create any materials that are abusive, harassing, tortious, defamatory, libelous, or invasive of another’s privacy;
                       iii. transmit any material that contains adware, malware, spyware, software viruses, or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;
                       iv. impersonate any person or entity, or otherwise misrepresent your affiliation with a person or entity; or
                       v. interfere with or disrupt the Sheetroom Services or servers or networks connected to the Sheetroom Services, or disobey any requirements, procedures, policies, or regulations of networks connected to the Sheetroom Services.</p>
                   <h3 id="5-personal-non-commercial-use-only">5. Personal, Non-Commercial Use Only</h3>
                   <p>You agree to use the Sheetroom Services only (a) as an end user, for your personal, non-commercial use or (b) as a teacher, for academic use by you and your students in individual classes. </p>
                   <h3 id="6-user-submissions-and-generated-materials">6. User Submissions and Generated Materials</h3>
                   <p>Sheetroom does not claim ownership of any materials (other than the underlying software and other materials of Sheetroom and its licensors used to generate such materials),  content, images, embeds, data, text, or other materials you submit and create for display or distribution to others through the Sheetroom Services, or the assignments generated therefrom (collectively, “User Submissions and Generated Materials”). As between Sheetroom and you, you own all rights to your User Submissions and Generated Materials. You grant to Sheetroom an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license, with the right to sublicense through multiple tiers, to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform, and publicly display or otherwise use your User Submissions and Generated Materials (in whole or in part) in connection with the operation of the Service or the promotion, advertising or marketing thereof, in any format or medium now known or later developed, without compensation or notification to or permission from the user of any kind. You acknowledge and agree that all right and title in the software code and other material used to create or display your User Submissions and Generated Materials is the property of Sheetroom, and you hereby assign all right and title in such material to Sheetroom. Sheetroom hereby grants you a license to such material (a) as an end user, for your personal, non-commercial use or (b) as a teacher, for academic use by you and your students in individual classes. Sheetroom does not pre-screen User Submissions and Generated Materials and you agree that you are solely responsible for all of your User Submissions and Generated Materials. Sheetroom is not required to host, display, or distribute any User Submissions and Generated Materials, and may remove at any time or refuse any User Submissions and Generated Materials. Sheetroom is not responsible for any loss, theft or damage of any kind to any User Submissions and Generated Materials. You represent and warrant that your User Submissions and Generated Materials, and Sheetroom’ authorized use thereof, do not and will not infringe the rights of any third party (including, without limitation, intellectual property rights, rights of privacy or publicity, or any other legal or moral rights).</p>
                   <h3 id="7-special-terms-for-schools">7. Special Terms for Schools</h3>
                   <p>a. <em>Fees</em>. If Sheetroom makes any Sheetroom Service available without charging a fee, then Sheetroom will not thereafter charge a fee to use such existing Sheetroom Service. The foregoing will not, however, prohibit Sheetroom from removing support for any Sheetroom Service or from charging a fee for any new Sheetroom Services that are complementary to, or may be used together with, such existing Sheetroom Service.
                       b. <em>Activity Sharing</em>. At the time you, as School user, submit to Sheetroom an activity you’ve developed using the Sheetroom Activity Builder (an “Activity”), you may elect to make your Activity public. If you do so, then you expressly authorize Sheetroom to (i) make your Activity available to other School users for use in individual classes with other students, (ii) allow other School users to copy and modify your Activity and use the modified version in individual classes with other students and (iii) modify your Activity and make the modified version available to other School users for use in individual classes with other students. In the case of any such use of your Activity (whether unmodified or modified), you will receive an attribution credit. If you elect to make your Activity public, in no event will Sheetroom authorize any third party to sell your Activity to others, nor will Sheetroom sell your activity itself, without your permission.</p>
                   <h3 id="8-copyright-infringement">8. Copyright Infringement</h3>
                   <p>Sheetroom respects the intellectual property rights of others. Accordingly, Sheetroom has a policy of removing User Submissions and Generated Materials that violate copyright law, and, in appropriate circumstances, suspending access to the Sheetroom Services (or any portion thereof) to any user who uses the Sheetroom Services in violation of copyright law, and/or terminating the account of any user who uses the Sheetroom Services in violation of copyright law. Pursuant to Title 17 of the United States Code, Section 512, Sheetroom has implemented procedures for receiving written notification of claimed copyright infringement and for processing such claims in accordance with such law. If you believe your copyright is being infringed by a user of the Sheetroom Services, please email a written notice to the following Sheetroom agent for notice of claims of copyright infringement.
                       Sheetroom, Inc.
                       Email: dmca@Sheetroom.com
                       Your written notice must: (a) contain your physical or electronic signature; (b) identify the copyrighted work alleged to have been infringed; (c) identify the allegedly infringing material in a sufficiently precise manner to allow Sheetroom to locate that material; (d) contain adequate information by which Sheetroom can contact you (including postal address, telephone number, and e-mail address); (e) contain a statement that you have a good faith belief that use of the copyrighted material is not authorized by the copyright owner, the copyright owner’s agent, or the law; (f) contain a statement that the information in the written notice is accurate; and (g) contain a statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</p>
                   <h3 id="9-feedback">9. Feedback</h3>
                   <p>If you choose to provide technical, business or other feedback to Sheetroom concerning the Sheetroom Services or any Sheetroom products or services (collectively, “Feedback”), Sheetroom will be free to use such Feedback without restriction. You understand and agree that the incorporation by Sheetroom of Feedback into any of its products or services does not grant you any proprietary rights therein.</p>
                   <h3 id="10-termination-and-suspension">10. Termination and Suspension</h3>
                   <p>Without limiting other remedies, Sheetroom may terminate or suspend your Sheetroom Services membership or suspend your access to all or part of the Sheetroom Services without notice if Sheetroom believes that you have violated these Terms or have engaged in conduct that violates applicable law or is otherwise harmful to the interests of Sheetroom, any other Sheetroom Services user, or any third party. You may discontinue your use of the Sheetroom Services at any time.</p>
                   <h3 id="11-fees">11. Fees</h3>
                   <p>Sheetroom reserves the right to charge fees for access to new Sheetroom Services. In no event will you be charged for access to any new Sheetroom Services, unless Sheetroom obtains your prior agreement to pay such fees. If you do not consent to the payment of such fees, however, Sheetroom may prohibit your access to that paid content or services. Details regarding the services you will receive in exchange for the payment of fees, as well as any payment terms and conditions that apply, will be disclosed to you prior to your agreement to pay such fees. All such terms will be deemed to be a part of (and are hereby incorporated by reference into) these Terms.</p>
                   <h3 id="12-password-and-security">12. Password and Security</h3>
                   <p>You are responsible for maintaining the confidentiality of your Sheetroom Services email and/or social login, and you are solely responsible for all activities that occur under your account. You agree to immediately notify Sheetroom of any unauthorized use of your account or any other breach of security related to the Sheetroom Services. </p>
                   <h3 id="13-third-party-services">13. Third Party Services</h3>
                   <p>Sheetroom may integrate with or provide links to certain third party Internet sites and services (collectively, such third parties, “Linked Partners”). The Linked Partner services made available through the Sheetroom Services or the integration of the such sites and services with the Sheetroom Services are for your convenience only and do not signify the endorsement by Sheetroom of such Partner sites or services.</p>
                   <h3 id="14-disclaimer-and-limitations-of-liability">14. Disclaimer and Limitations of Liability</h3>
                   <p>a. You agree that use of the Sheetroom services is at your sole risk. The Sheetroom services are provided on an “as is” and “as available” basis. Sheetroom expressly disclaims all warranties of any kind, whether express or implied, with respect to the Sheetroom services and all services provided by any of our partner (whether api partners, linked partners, or otherwise), including, but not limited to, the implied warranties of merchantability, fitness for a particular use or purpose, and non-infringement. You acknowledge that access to data and materials (including, but not limited to, your or others’ user submissions and generated materials) available through the Sheetroom services is not guaranteed and that Sheetroom will not be responsible to you for any loss of data or materials caused by the Sheetroom services or their unavailability. You understand and agree that any data, materials, services and/or information downloaded or otherwise obtained through the use of the Sheetroom services is done at your own discretion and risk and that you will be solely responsible for any damage arising therefrom.
                       b. Under no circumstances will Sheetroom or its officers, employees, directors, shareholders, agents, or licensors be liable under any theory of liability (whether in contract, tort, statutory, or otherwise) for any damages whatsoever, including direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of money, revenues, profits, goodwill, use, data or other intangible losses (even if such parties were advised of, knew of or should have known of the possibility of such damages), resulting from your (or anyone using your account’s) use of the Sheetroom services.
                       c. If, notwithstanding these Terms, Sheetroom is found to be liable to you or any third party in connection with your use of the Sheetroom services, the total liability of Sheetroom and its officers, employees, directors, shareholders, agents, or licensors to you or to any third party is limited to one hundred U.S. Dollars ($100).
                       d. <em>Exclusions And Limitations</em>. Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for certain damages. Accordingly, some of the above limitations and disclaimers may not apply to you. To the extent that Sheetroom may not, as a matter of applicable law, disclaim any implied warranty or limit its liabilities, the scope and duration of such warranty and the extent of Sheetroom’ liability will be the minimum permitted under such applicable law.</p>
                   <h3 id="15-indemnification">15. Indemnification</h3>
                   <p>You agree to indemnify, defend, and hold harmless Sheetroom and its officers, directors, employees, consultants and agents from and against any and all claims, liabilities, damages, losses, costs, expenses, fees (including reasonable attorneys’ fees) that such parties may incur as a result of or arising from your (or anyone using your account’s) violation of these Terms. Sheetroom reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with Sheetroom’ defense of such claim.</p>
                   <h3 id="16-intellectual-property">16. Intellectual Property</h3>
                   <p>“Sheetroom” and the Sheetroom logo, and certain other of the names, logos, and materials displayed in the Sheetroom Services, may constitute trademarks, trade names, or service marks (“Marks”) of Sheetroom or other entities. You are not authorized to use any such Marks. Ownership of all such Marks and the goodwill associated therewith remains with Sheetroom or those other entities. The content on the Sheetroom Services (the “Content”), including without limitation, the software, graphs, text and graphics, is protected under United States and international copyright laws, is subject to other intellectual property and proprietary rights and laws, and is owned by Sheetroom or its licensors. Other than with respect to your own User Submissions and Generated Materials, (a) the Content may not be copied, modified, reproduced, republished, posted, transmitted, sold, offered for sale, or redistributed in any way without the prior written permission of Sheetroom and its applicable licensors; and (b) you must abide by all copyright notices, information, or restrictions contained in or attached to any Content.</p>
                   <h3 id="17-miscellaneous">17. Miscellaneous</h3>
                   <p><em>Entire Agreement</em>. These Terms and our Privacy Policy, together with any additional terms to which you agree when using particular elements of the Sheetroom Services (e.g., terms relating to the payment of fees for certain Sheetroom Services), constitute the entire and exclusive and final statement of the agreement between you and Sheetroom with respect to the subject matter hereof, and govern your use of the Sheetroom Services, superseding any prior agreements or negotiations between you and Sheetroom with respect to the subject matter hereof.
                       <em>Governing Law</em>. These Terms and the relationship between you and Sheetroom will be governed by the laws of the State of California as applied to agreements made, entered into, and performed entirely in California by California residents, notwithstanding your actual place of residence. All lawsuits arising from or relating to these Terms or your use of the Sheetroom Services will be brought in the Federal or State courts located in San Francisco County, California, and you hereby irrevocably submit to the exclusive personal jurisdiction of such courts for such purpose.
                       <em>Additional Terms</em>. The failure of Sheetroom to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision. If any provision of these Terms is found by a court of competent jurisdiction to be invalid, you nevertheless agree that the court should endeavor to give effect to the intentions of Sheetroom and you as reflected in the provision, and that the other provisions of these Terms remain in full force and effect. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Sheetroom Services or these Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred. The section titles in these Terms are for convenience only and have no legal or contractual effect. These Terms will remain in full force and effect notwithstanding any termination of your use of the Sheetroom Services. If access to the Sheetroom Services is licensed to the United States government or any agency thereof, then the Sheetroom Services will be deemed to be “commercial computer software” and “commercial computer software documentation,” pursuant to DFARS Section 227.7202 and FAR Section 12.212, respectively, as applicable. Any use, reproduction, release, performance, display, or disclosure of the Sheetroom Services and any accompanying documentation by the U.S. Government will be governed solely by these Terms and is prohibited except to the extent expressly permitted by these Terms.</p>
                   <h2 id="payment-refunds-and-plan-changes">18. Payment, Refunds, and Plan Changes</h2>
                   <ol>
                       <li>If you are using a free version of one of our Services, it is really free: we do not ask you for your credit card and — just like for customers who pay for our Services — we do not sell your data.</li>
                       <li>For paid Services that offer a free trial, we explain the length of trial when you sign up. After the trial period, you need to pay in advance to keep using the Service. If you do not pay, we will freeze your account and it will be inaccessible until you make payment. If your account has been frozen for a while, we will queue it up for auto-cancellation. See our <a href="../cancellation/index.md">Cancellation policy</a> for more details.</li>
                       <li>If you are upgrading from a free plan to a paid plan, we will charge your card immediately and your billing cycle starts on the day of upgrade. For other upgrades or downgrades in plan level, the new rate starts from the next billing cycle.</li>
                       <li>All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities. Where required, we will collect those taxes on behalf of the taxing authority and remit those taxes to taxing authorities. Otherwise, you are responsible for payment of all taxes, levies, or duties.</li>
                       <li>We process refunds according to our <a href="/refund-policy">Fair Refund policy</a>.</li>
                   </ol>
                   <h3 id="18-modifications-to-terms-and-services">19. Modifications To Terms and Services</h3>
                   <p>a. <em>Modifications</em>. These Terms may be revised periodically and this will be reflected in the “date last modified” set forth below. Your continued use of the Sheetroom Services following such update constitutes your agreement to the revised Terms. If you object to any such changes, your sole recourse will be to cease using the Sheetroom Services. Continued use of the Sheetroom Services following notice of any such changes will indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes. Sheetroom reserves the right to modify or discontinue the Sheetroom Services with or without notice to you.
                       b. <em>Date Last Modified</em>. These Terms were last modified on September 2, 2020.</p>
               </div>

            </div>
        </div>
        <Footer/>
    </>
}

export default Terms
